spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vladprodimport_db?autoReconnect=true&useSSL=false
    username: root
    password: 10114
    initialization-mode: always
