spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
