spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vladprodimport_db?autoReconnect=true&useSSL=false
    username: root
    password: 10114
    initialization-mode: always
app:
  jwtSecret: HfEGckFc4ZxlM9YbC-UxDOQRmofT85j5Xv74BdsfUTyEFRe1an-7mwlF6PYkfbpAf85k_l9qOs1lhC4JpdboAQ
  #  jwtExpirationInMs means how much time User will be have an access-token ,starting with auth
  #  (value in ms)
  jwtExpirationInMs: 604800000

